name: Action para crear imagen y tagearla

inputs:
 username:
  required: true
  default: usuario

runs:
 using: "composite"
 outputs:
   image_name: ${{steps.nombre-imagen.outputs.image_name}}
 steps:
 - name: Extraer version
   id: version
   run: |
    VERSION=$(jq -r '.version' package.json)
    echo "VERSION=$VERSION" >> $GITHUB_ENV
    echo "app_version=$VERSION" >> $GITHUB_OUTPUT
   shell: bash

 - name: Extraer nombre
   id: nombre
   run: |
    NOMBRE=$(jq -r '.name' package.json)
    echo "NOMBRE=$NOMBRE" >> $GITHUB_ENV
    echo "app_name=$NOMBRE" >> $GITHUB_OUTPUT
   shell: bash

 - name: Nombre tageado de la imagen
   id: nombre_imagen
   run: |
    NOMBRE_IMAGEN="${{inputs.username}}/${{steps.nombre.outputs.app_name}}:${{steps.version.outputs.app_version}}"
    echo "image_name=$NOMBRE_IMAGEN" >> $GITHUB_OUTPUT
   shell: bash
