name: Action para crear imagen y tagearla

inputs:
  image_name:
   required: true
  version:
   required: true

runs:
 using: "composite"
 steps:
 - name: Nombre tageado de la imagen
   id: nombre_imagen
   run: |
    NOMBRE_IMAGEN="${{vars.DOCKERHUB_USERNAME}}/${{inputs.image_name}}:${{inputs.version}}"
    echo "image_name=$NOMBRE_IMAGEN" >> $GITHUB_ENV
   shell: bash
