name: Action para crear imagen y tagearla

inputs:
  username:
   required: true
  image_name:
   required: true
  version:
   required: true

runs:
 using: "composite"
 steps:
 - name: Nombre tageado de la imagen
   id: nombre_imagen
   run: |
    NOMBRE_IMAGEN="${{inputs.username}}/${{inputs.image_name}}:${{steps.version}}"
    echo "image_name=$NOMBRE_IMAGEN" >> $GITHUB_ENV
   shell: bash

outputs:
  image_name: ${{ steps.nombre_imagen.outputs.image_name }}
