name: Workflow para crear la imagen

on:
 workflow_dispatch:

jobs:
 cargar:
  runs-on: ubuntu-latest
  steps:
  - name: hola
    id: prueba
    uses: ./.github/workflows/workflowCI.yml

  - name: imprimir   
    run: echo "${{steps.prueba.outputs.image_name_ci}}"

 descargar:
  needs: cargar
  if: github.ref == 'refs/heads/development' #CAMBIAR A MAIN
  uses: ./.github/workflows/workflowCD.yml
  with:
   image_name: ${{needs.cargar.outputs.image_name}}
