name: Workflow para crear la imagen

on:
 workflow_dispatch:

jobs:
 cargar:
  runs-on: ubuntu-latest
  outputs:
   image_name: ${{steps.nombre_imagen.outputs.image_name}}
  steps:
  - uses: actions/checkout@v3
  
  - name: Cargar nombre imagen
    id: cargar_imagen
    uses: ./action

 imprimir:
  runs-on: ubuntu-latest
  needs: cargar
  steps:
  - name: Imprimir
    run: echo ${{needs.cargar.outputs.image_name}}
