name: Workflow para crear la imagen

on:
 workflow_dispatch:

jobs:
 Crear:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  
  - name: Cargar nombre imagen
    id: cargar
    uses: ./action
    
  - name: Imprimir
    run: echo ${{steps.nombre_imagen.outputs.image_name}}
    shell: bash
