name: Denominar entornos

on:
 workflow_call:
  outputs: 
   entorno:
    value: ${{jobs.entorno.outputs.entorno}}

jobs:
 entorno:
  runs-on: ubuntu-latest
  outputs:
   entorno: ${{steps.elegir.outputs.entorno}}
  steps:
  - name: Elegir entorno
    id: elegir
    run: |
     if [ "${{github.ref}}" == "refs/heads/main" ]; then
      echo ENTORNO="producción" >> GITHUB_ENV
      echo "entorno=$ENTORNO" >> GITHUB_OUTPUT
     elif [ "${{github.ref}}" == "refs/heads/development" ]; then
      echo ENTORNO="UAT" >> GITHUB_ENV
      echo "entorno=$ENTORNO" >> GITHUB_OUTPUT
     fi

  - name: Mostrar
    run: echo "${{steps.elegir.outputs.entorno}}"
