name: Workflow para crear la imagen

on:
 workflow_dispatch:

jobs:
 cargar:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  
  - uses: ./.github/workflows/workflowCI.yml

 descargar:
  needs: cargar
  if: github.ref == 'refs/heads/development' #CAMBIAR A MAIN
  uses: ./.github/workflows/workflowCD.yml
  with:
   image_name: ${{needs.cargar.outputs.image_name}}
