name: Workflow para crear la imagen

on:
 workflow_dispatch:

jobs:
 cargar:
  uses: ./.github/workflows/workflowCI.yml
  secrets: inherit

 descargar:
  needs: cargar
  if: github.ref == 'refs/heads/main'
  uses: ./.github/workflows/workflowCD.yml
  with:
   image_name_ci: ${{needs.cargar.outputs.image_name_ci}}
